CREATE TABLE source_documents(document_id VARCHAR PRIMARY KEY, source_id VARCHAR NOT NULL REFERENCES evidence_sources(source_id), document_type VARCHAR NOT NULL, record_hash VARCHAR NOT NULL);
CREATE TABLE source_files(file_id VARCHAR PRIMARY KEY, document_id VARCHAR NOT NULL REFERENCES source_documents(document_id), path VARCHAR NOT NULL, sha256 VARCHAR NOT NULL, immutable BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE source_locations(location_id VARCHAR PRIMARY KEY, source_id VARCHAR NOT NULL REFERENCES evidence_sources(source_id), location_type VARCHAR NOT NULL, page VARCHAR, section VARCHAR, object_label VARCHAR, record_json JSON NOT NULL);
CREATE TABLE source_identifiers(identifier_id VARCHAR PRIMARY KEY, source_id VARCHAR NOT NULL REFERENCES evidence_sources(source_id), scheme VARCHAR NOT NULL, value VARCHAR NOT NULL, UNIQUE(scheme,value));
CREATE TABLE source_retrieval_events(retrieval_id VARCHAR PRIMARY KEY, source_id VARCHAR NOT NULL, provider VARCHAR NOT NULL, accessed_at TIMESTAMP NOT NULL, response_hash VARCHAR NOT NULL, response_path VARCHAR NOT NULL);
CREATE TABLE compound_aliases(alias_id VARCHAR PRIMARY KEY, compound_id VARCHAR NOT NULL, alias VARCHAR NOT NULL, source_id VARCHAR);
CREATE TABLE compound_source_links(compound_id VARCHAR NOT NULL, source_id VARCHAR NOT NULL, PRIMARY KEY(compound_id,source_id));
CREATE TABLE protein_sequences(sequence_id VARCHAR PRIMARY KEY, variant_id VARCHAR NOT NULL, sequence_kind VARCHAR NOT NULL, sequence_hash VARCHAR NOT NULL, sequence VARCHAR NOT NULL);
CREATE TABLE variant_aliases(alias_id VARCHAR PRIMARY KEY, variant_id VARCHAR NOT NULL, alias VARCHAR NOT NULL, source_id VARCHAR);
CREATE TABLE variant_accessions(accession_id VARCHAR PRIMARY KEY, variant_id VARCHAR NOT NULL, accession VARCHAR NOT NULL, accession_type VARCHAR NOT NULL, source_database VARCHAR NOT NULL, verification_status VARCHAR NOT NULL);
CREATE TABLE variant_source_links(variant_id VARCHAR NOT NULL, source_id VARCHAR NOT NULL, PRIMARY KEY(variant_id,source_id));
CREATE TABLE mutation_observations(observation_id VARCHAR PRIMARY KEY, variant_id VARCHAR NOT NULL, reference_sequence_hash VARCHAR NOT NULL, author_mutation VARCHAR NOT NULL, author_numbering VARCHAR NOT NULL, bbl_numbering VARCHAR, verification_status VARCHAR NOT NULL);
CREATE TABLE numbering_mappings(mapping_id VARCHAR PRIMARY KEY, observation_id VARCHAR NOT NULL, method VARCHAR NOT NULL, verified BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE protein_structures(structure_id VARCHAR PRIMARY KEY, variant_id VARCHAR, source_id VARCHAR NOT NULL, database_id VARCHAR NOT NULL, verification_status VARCHAR NOT NULL);
CREATE TABLE structure_chains(chain_id VARCHAR PRIMARY KEY, structure_id VARCHAR NOT NULL, chain_label VARCHAR NOT NULL, construct_start INTEGER, construct_end INTEGER, sequence_hash VARCHAR);
CREATE TABLE protocols(protocol_id VARCHAR PRIMARY KEY, source_id VARCHAR NOT NULL, record_json JSON NOT NULL);
CREATE TABLE assay_conditions(condition_id VARCHAR PRIMARY KEY, assay_id VARCHAR NOT NULL, condition_type VARCHAR NOT NULL, original_value VARCHAR, original_units VARCHAR, record_json JSON NOT NULL);
ALTER TABLE measurements ADD COLUMN IF NOT EXISTS source_location_id VARCHAR;
CREATE VIEW current_verified_sources AS SELECT * FROM evidence_sources WHERE json_extract_string(record_json,'$.verification_status') IN ('source_verified','dual_curator');
CREATE VIEW current_verified_variants AS SELECT * FROM protein_variants WHERE json_extract_string(record_json,'$.verification_status')='source_verified';
CREATE VIEW biochemical_measurement_matrix AS SELECT m.compound_id,a.enzyme_variant_id,m.endpoint_type,m.original_value,m.original_units FROM measurements m JOIN assays a ON m.assay_id=a.internal_assay_id WHERE json_extract_string(a.record_json,'$.assay_category')='BIOCHEMICAL';
CREATE VIEW microbiological_measurement_matrix AS SELECT m.compound_id,a.enzyme_variant_id,m.endpoint_type,m.original_value,m.original_units FROM measurements m JOIN assays a ON m.assay_id=a.internal_assay_id WHERE json_extract_string(a.record_json,'$.assay_category')='MICROBIOLOGICAL';
CREATE VIEW unresolved_identity_conflicts AS SELECT * FROM variant_accessions WHERE verification_status IN ('unverified','identity_pending_verification');
CREATE VIEW unresolved_measurement_conflicts AS SELECT compound_id,assay_id,endpoint_type,count(*) record_count FROM measurements GROUP BY ALL HAVING count(DISTINCT concat(relation,original_value,original_units))>1;
CREATE VIEW excluded_records_audit AS SELECT * FROM measurements WHERE exclusion_status='excluded';
CREATE VIEW source_provenance_chain AS SELECT s.source_id,i.scheme,i.value,r.provider,r.accessed_at,r.response_hash FROM evidence_sources s LEFT JOIN source_identifiers i USING(source_id) LEFT JOIN source_retrieval_events r USING(source_id);
